version: '3.7'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: docker-wordpress
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: nome_dobancodedados
      WORDPRESS_DB_USER: usuario_dobancodedados
      WORDPRESS_DB_PASSWORD: senha_dobandodedados

  db:
    image: mariadb:latest
    container_name: www-mariadb
    volumes:
      - ./wordpress_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senhadoroot_dobancodedados
      MYSQL_DATABASE: nome_dobancodedados
      MYSQL_USER: usuario_dobancodedados
      MYSQL_PASSWORD: senha_dobandodedados
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: www-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: senhadoroot_dobancodedados

volumes:
  db_data: {}