version: '2'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:4.9.4
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: root
    ports:
      - 80:80
      - 443:443
    networks: 
      - back

  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root #default USER is root
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - back
networks:
  back:

volumes:
  db_data: